# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc25e963c30fc463037b5dd34f56792c23fce5fb4f77616e182d8948f5cfe66a9d21066d7ec9735dcb4d6f2dd15f9bedf67e3a49d5224649622a3a4264eaf12d

test:
  secret_key_base: 8e45a62c404705949822d9e46072fca79af812a56df98c6e565373c8d8281a7844f3699fba9f9e68d4d3a418fc0a6bacbe99327b6e556ce078c8cc59ff29e3f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
